Sources/OS.Web/Models/OrderDetailsViewModel.cs
using OS.Business.Domain;

namespace OS.Web.Models
{
    public class OrderDetailsViewModel
    {
        public Order Order { get; set; }
    }
}

Sources/OS.Web/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using OS.Business.Domain;
using OS.Business.Logic;
using OS.Web.Models;
using Recaptcha.Web;
using Recaptcha.Web.Mvc;

namespace OS.Web.Controllers
{
    public class OrdersController : Controller
    {
        private readonly OrdersBL _ordersBL;

        public OrdersController(OrdersBL ordersBL)
        {
            _ordersBL = ordersBL;
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View("Edit");
        }

        [HttpPost]
        public ActionResult Create(EditOrderViewModel model)
        {
            RecaptchaVerificationHelper recaptchaHelper = this.GetRecaptchaVerificationHelper();
            if (string.IsNullOrEmpty(recaptchaHelper.Response))
            {
                ModelState.AddModelError("", "Captcha відповідь не може бути пустою.");
                return View("Edit", model);
            }

            RecaptchaVerificationResult recaptchaResult = recaptchaHelper.VerifyRecaptchaResponse();
            if (recaptchaResult != RecaptchaVerificationResult.Success)
            {
                ModelState.AddModelError("", "Невірна captcha відповідь.");
                return View("Edit", model);
            }

            HttpCookie consumerBasketRawDataCookie = Request.Cookies["ConsumerBasket"];
            if (consumerBasketRawDataCookie == null)
            {
                ModelState.AddModelError("", "Не вибрано жодного товару для покупки");
            }

            if (ModelState.IsValid)
            {
                List<ProductInBasketViewModel> productInBasketViewModels = JsonConvert.DeserializeObject<List<ProductInBasketViewModel>>(
                    HttpContext.Server.UrlDecode(consumerBasketRawDataCookie.Value));

                Order order = _ordersBL.CreateOrder(new CreateOrderQuery
                    {
                        Person = new CreateOrderQuery.AddPersonQuery
                            {
                                Email = model.Email,
                                MiddleName = model.MiddleName,
                                LastName = model.LastName,
                                PhoneNumber = model.PhoneNumber,
                                FirstName = model.FirstName
                            },
                        OrderedProducts = new List<CreateOrderQuery.AddOrderedProductQuery>(
                            productInBasketViewModels.Select(
                                p => new CreateOrderQuery.AddOrderedProductQuery
                                    {
                                        ProductId = p.Id,
                                        Quantity = p.Quantity
                                    }).ToList()),
                        AdditionalComment = model.AdditionalComment
                    });
                TempData[Constants.TempDataKeys.ORDER_ID] = order.Id;
                return RedirectToAction("OrderDetails", new {orderId = order.Id});
            }

            return View("Edit", model);
        }

        public ActionResult OrderDetails(int orderId)
        {
            HttpCookie cookie = new HttpCookie("ConsumerBasket");
            cookie.Expires = DateTime.Now.AddDays(-1);
            Response.Cookies.Set(cookie);

            if (TempData[Constants.TempDataKeys.ORDER_ID] != null)
            {
                orderId = (int) TempData[Constants.TempDataKeys.ORDER_ID];
            }

            Order order = _ordersBL.GetById(orderId);
            OrderDetailsViewModel viewModel = new OrderDetailsViewModel
                {
                    Order = order
                };

            return View(viewModel);
        }
    }
}

Sources/OS.Web/Views/Orders/Edit.cshtml
@using OS.Web.Models
@using Recaptcha.Web.Mvc
@model EditOrderViewModel

@{
    Layout = "../Shared/_publicLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <section id="editOrder">
            @using (Html.BeginForm("Create", "Orders", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
            {
                <h4>
                    ОФормлення замовлення
                </h4>
                <hr/>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.FirstName, new {@class = "col-md-2 control-label"})
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.FirstName, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.FirstName, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.LastName, new {@class = "col-md-2 control-label"})
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.LastName, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.LastName, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.MiddleName, new {@class = "col-md-2 control-label"})
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.MiddleName, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.MiddleName, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new {@class = "col-md-2 control-label"})
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.Email, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.Email, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.AdditionalComment, new {@class = "col-md-2 control-label"})
                    <div class="col-md-6">
                        @Html.TextAreaFor(m => m.AdditionalComment, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.AdditionalComment, "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-6">
                        @Html.Recaptcha(language: "uk")
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-4">
                        <input type="submit" value="Зберегти" class="btn btn-primary" />
                        <span></span>
                        <input type="reset" class="btn btn-default" value="Відміна" onclick="goBack()">    
                    </div>
                </div>
            }
        </section>
    </div>
</div>


@section scripts
{
}

Sources/OS.Web/Views/Orders/OrderDetails.cshtml
@using OS.Web.Models
@model OrderDetailsViewModel

@{
    Layout = "../Shared/_publicLayout.cshtml";
}

<h4>Замовлення</h4>
<hr />

Замовлення підтверджено. Номер замовлення @Model.Order.Id .

@section scripts
{}