Sources/OS.Web/Controllers/FilesController.cs
using System.Web.Mvc;
using System.Web.UI;
using OS.Business.Logic;
using File = OS.Business.Domain.File;

namespace OS.Web.Controllers
{
    public class FilesController : Controller
    {
        private readonly FilesBL _filesBl;

        public FilesController(FilesBL filesBL)
        {
            _filesBl = filesBL;
        }

        [OutputCache(Duration = 3600, Location = OutputCacheLocation.Client, VaryByParam = "id")]
        public ActionResult GetFileContent(int id)
        {
            File file = _filesBl.GetFile(id);

            return new FileContentResult(file.Data, file.ContentContentType.ToString());
        }
    }
}

Sources/OS.Web/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using OS.Business.Domain;
using OS.Business.Logic;
using OS.Web.Models;
using OS.Web.Models.ProductViewModels;

namespace OS.Web.Controllers
{
    [RoutePrefix("")]
    public class HomeController : Controller
    {
        private readonly ProductCategoriesBL _productCategoriesBL;
        private readonly ProductsBL _productsBL;

        public HomeController(ProductCategoriesBL productCategoriesBL, ProductsBL productsBL)
        {
            _productCategoriesBL = productCategoriesBL;
            _productsBL = productsBL;
        }

        public ActionResult Index(string searchTerm)
        {
            HomePageViewModel viewModel = new HomePageViewModel();
            viewModel.RootCategories = _productCategoriesBL.GetCategories(null).Select(productCategory => new HorizontalCategoryItemViewModel
            {
                ProductCategory = productCategory,
                IsSelected = false
            }).ToList();

            viewModel.SelectedCategory = null;
            viewModel.Products = _productsBL.Get(new ProductsFilter
                {
                    Text = searchTerm,
                    Publish = true
                }).Entities;

            return View(viewModel);
        }

        [Route("categories/{categoryId:int}")]
        public ActionResult ChangeCategory(int categoryId)
        {
            HomePageViewModel viewModel = new HomePageViewModel();
            viewModel.RootCategories = _productCategoriesBL.GetCategories(null).Select(productCategory => new HorizontalCategoryItemViewModel
            {
                ProductCategory = productCategory,
                IsSelected = productCategory.Id == categoryId
            }).ToList();

            viewModel.SelectedCategory = _productCategoriesBL.GetById(categoryId);
            viewModel.Products = _productsBL.Get(new ProductsFilter
            {
                ParentId = categoryId,
                Publish = true
            }).Entities;

            return View("Index", viewModel);
        }

        [Route("categories/{categoryId:int}/products/{productId:int}")]
        public ActionResult Details(int productId, int categoryId)
        {
            ProductDetailsViewModel model = new ProductDetailsViewModel
            {
                CategoryId = categoryId,
                Product = _productsBL.GetById(productId)
            };
            return View("Details", model);
        }
    }
}

Sources/OS.Web/Views/Home/Create.cshtml
@using OS.Web.Models.ProductViewModels
@model ProductCreateOrEditViewModel

@{
    Layout = "~/Views/Shared/_adminEditLayout.cshtml";
}

@section editor
{
    Editor
}

Sources/OS.Web/Views/Home/Details.cshtml
@using OS.Business.Domain
@using OS.Web.Models.ProductViewModels
@model ProductDetailsViewModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_publicLayout.cshtml";
}

@{
    ProductPhoto mainPhoto = Model.Product.Photos.SingleOrDefault(x => x.IsMain);

    mainPhoto = mainPhoto != null ? mainPhoto : Model.Product.Photos.FirstOrDefault();
}
  
<div class="row">
    <div class="col-md-4">
        @if (mainPhoto != null)
        {
            <img height="171" width="180" src="@Url.Action("GetFileContent", "Files", new {id = mainPhoto.Id})"/>
        }
    </div>
    <div class="col-md-8">
        <div class="row" style="padding-bottom: 10px; vertical-align: middle">
            <span class="product-code-block">
                <span class="product-code-lable">Код товару: </span><span class="product-code" style="vertical-align: middle">@Model.Product.Code</span>
            </span>
        </div>
        <div class="row">
            @Html.Raw(Model.Product.Description)
        </div>
    </div>
</div>


@{
    string returnUrl = Request.UrlReferrer != null ? Request.UrlReferrer.LocalPath : Url.Action("Index", "Home");
}

<div class="row">
    <div class="col-md-offset-4">
        <span class="btn btn-success btn-buy-product" style="display: none" productId="@Model.Product.Id" categoryId="@Model.CategoryId" productPrice="@Model.Product.Price">Купити</span>    
        <a class="btn btn-default" href="@returnUrl">Повернутися до пошуку товарів</a>
    </div>
</div>

<div class="row" style="margin-left: 0; margin-right: 0; margin-top: 20px;">
    <div id="productPhotos" class="row list-group">
        @{
            IEnumerable<ProductPhoto> restPhotos = Model.Product.Photos.Where(x => !x.IsMain && !x.IsDeleted).ToList();
        }

        @foreach (ProductPhoto productPhoto in restPhotos)
        {
            <div class="os-item col-xs-3 col-lg-3">
                <div class="thumbnail">
                    <a href="@Url.Action("GetFileContent", "Files", new {id = productPhoto.Id})" target="_blank">
                        <img height="171" width="180" src="@Url.Action("GetFileContent", "Files", new {id = productPhoto.Id})" />
                    </a>
                </div>
            </div>
        }
    </div>
</div>

@section scripts
{

}

Sources/OS.Web/Views/Home/Index.cshtml
@using OS.Business.Domain
@using OS.Web.Models
@model HomePageViewModel

@{
    Layout = "../Shared/_publicLayout.cshtml";
}

@if (Model.Products.Count > 0)
{
    <div id="products" class="table-row list-group">
        @foreach (Product product in Model.Products)
        {
            @Html.Partial("_productItem", product)
        }
    </div>
}
else
{
    <div class="alert alert-info">
        Ця категорія не містить продуктів
    </div>
}

@section scripts
{
}

Sources/OS.Web/Views/Home/_productItem.cshtml
@using OS.Business.Domain
@model Product

@{
    int categoryId = Model.Categories.First().Id;
}

<div class="os-item col-xs-3 col-lg-3">
    <div class="thumbnail">
        <a href="@Url.Action("Details", "Home", new
                         {
                             productId = @Model.Id,
                             categoryId = categoryId
                         })">

            @Html.Partial("_productListItemImage", Model)
            <div class="caption">
                <h5 class="group inner list-group-item-heading">
                    @Model.Name
                </h5>
                <p class="group inner list-group-item-text">
                    @Model.ShortDescription
                </p>

                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <b>
                            @Model.Price
                        </b>
                    </div>
                    <div class="col-xs-12 col-md-6">
                        <span class="btn btn-success btn-buy-product" style="display: none" productId="@Model.Id" categoryId="@categoryId" productPrice="@Model.Price">Купити</span>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>