Sources/OS.Web/Models/ConsumerBasketViewModel.cs
using System.Collections.Generic;
using OS.Business.Domain;

namespace OS.Web.Models
{
    public class ProductToBuyDescriptor
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }

        public int CategoryId { get; set; }
    }

    public class ConsumerBasketViewModel
    {
        public ConsumerBasketViewModel()
        {
            ProductToByDescriptors = new List<ProductToBuyDescriptor>();
        }

        public List<ProductToBuyDescriptor> ProductToByDescriptors { get; private set; }
    }
}

Sources/OS.Web/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using OS.Business.Domain;
using OS.Business.Logic;

namespace OS.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ProductCategoriesBL _productCategoriesBL;

        public CategoriesController(ProductCategoriesBL productCategoriesBL)
        {
            _productCategoriesBL = productCategoriesBL;
        }

        [ChildActionOnly]
        public ActionResult VerticalCategorySelector()
        {
            PagedProductCategoryListResult rootCategories = _productCategoriesBL.SearchByFilter(new ProductCategoriesFilter
                {
                    ParentId = null,
                    IgnoreParentId = false,
                    IncludeDeleted = false,
                    Publish = true
                });

            VerticalCategorySelectorViewModel model = new VerticalCategorySelectorViewModel();
            model.Categories = new List<VerticalCategorySelectorItemViewModel>();

            foreach (ProductCategory productCategory in rootCategories.Entities)
            {
                VerticalCategorySelectorItemViewModel verticalCategorySelectorItemViewModel = new VerticalCategorySelectorItemViewModel
                    {
                        Id = productCategory.Id,
                        Name = productCategory.Name,
                        ProductsCount = productCategory.Products.Count
                    };
                model.Categories.Add(verticalCategorySelectorItemViewModel);

                AddChildCategories(verticalCategorySelectorItemViewModel.ChildCategories, productCategory);
            }

            return PartialView("_verticalCategorySelector", model);
        }

        private void AddChildCategories(List<VerticalCategorySelectorItemViewModel> verticalCategorySelectorItemViewModels, ProductCategory parentCategory)
        {
            PagedProductCategoryListResult childCategories = _productCategoriesBL.SearchByFilter(new ProductCategoriesFilter
                {
                    ParentId = parentCategory.Id,
                    IgnoreParentId = false,
                    IncludeDeleted = false,
                    Publish = true
                });
                
            foreach (ProductCategory productCategory in childCategories.Entities)
            {
                VerticalCategorySelectorItemViewModel verticalCategorySelectorItemViewModel = new VerticalCategorySelectorItemViewModel
                {
                    Id = productCategory.Id,
                    Name = productCategory.Name,
                    ProductsCount = productCategory.Products.Count
                };
                verticalCategorySelectorItemViewModels.Add(verticalCategorySelectorItemViewModel);

                AddChildCategories(verticalCategorySelectorItemViewModel.ChildCategories, productCategory);
            }
        }
    }
}

Sources/OS.Web/Controllers/ConsumerBasketController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using OS.Business.Domain;
using OS.Business.Logic;
using OS.Web.Models;

namespace OS.Web.Controllers
{
    public class ConsumerBasketController : Controller
    {
        private readonly ProductsBL _productsBL;

        public ConsumerBasketController(ProductsBL productsBL)
        {
            _productsBL = productsBL;
        }

        public ActionResult Index()
        {
            HttpCookie consumerBasketRawDataCookie = Request.Cookies["ConsumerBasket"];

            ConsumerBasketViewModel consumerBasketViewModel = new ConsumerBasketViewModel();

            if (consumerBasketRawDataCookie != null)
            {
                List<ProductInBasketViewModel> productInBasketViewModels = JsonConvert.DeserializeObject<List<ProductInBasketViewModel>>(
                    HttpContext.Server.UrlDecode(consumerBasketRawDataCookie.Value));
            
                List<Product> products = _productsBL.GetByIds(productInBasketViewModels.Select(x => x.Id));

                consumerBasketViewModel.ProductToByDescriptors.AddRange(products.Select(product =>
                {
                    ProductInBasketViewModel productInBasketViewModel = productInBasketViewModels.Single(x => x.Id == product.Id);
                    return new ProductToBuyDescriptor
                        {
                            Product = product,
                            Quantity = productInBasketViewModel.Quantity,
                            CategoryId = productInBasketViewModel.CategoryId
                        };
                }));
            }
            
            return View(consumerBasketViewModel);
        }
    }
}

Sources/OS.Web/Controllers/HtmlContentsController.cs
using System.Web.Mvc;
using OS.Business.Domain;
using OS.Business.Logic;
using OS.Web.Controllers.Administration;
using OS.Web.Models.HtmlContentViewModels;

namespace OS.Web.Controllers
{
    public class HtmlContentsController : BaseAdminController
    {
        private readonly HtmlContentsBL _htmlContentsBL;

        public HtmlContentsController(HtmlContentsBL htmlContentsBL)
        {
            _htmlContentsBL = htmlContentsBL;
        }

        public ActionResult Edit(HtmlContentCode htmlContentCode)
        {
            HtmlContentCreateOrEditViewModel model;

            HtmlContent htmlContent = _htmlContentsBL.GetByCode(htmlContentCode);

            if (htmlContent != null)
            {
                model = new HtmlContentCreateOrEditViewModel
                    {
                        Text = htmlContent.Text,
                        Code = htmlContent.Code,
                        Id = htmlContent.Id == 0 ? (int?) null : htmlContent.Id
                    };
            }
            else
            {
                model = new HtmlContentCreateOrEditViewModel
                    {
                        Code = htmlContentCode
                    };
            }

            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Index(HtmlContentCode htmlContentCode)
        {
            HtmlContent htmlContent = _htmlContentsBL.GetByCode(htmlContentCode) ?? new HtmlContent
                {
                    Code = htmlContentCode
                };

            return View(htmlContent);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Save(HtmlContentCreateOrEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                HtmlContent htmlContent;
                if (model.Id.HasValue)
                {
                    htmlContent = _htmlContentsBL.GetById(model.Id.Value);
                }
                else
                {
                    htmlContent = new HtmlContent();
                }

                htmlContent.Code = model.Code;
                htmlContent.Text = model.Text;
                _htmlContentsBL.Update(htmlContent);

                model.Id = htmlContent.Id;
            }

            return RedirectToAction("Index", new
                {
                    htmlContentCode = model.Code
                });
        }
    }
}

Sources/OS.Web/Controllers/NotFoundController.cs
using System.Web.Mvc;

namespace OS.Web.Controllers
{
    public class NotFoundController : Controller
    {
        [Route("notfound")]
        public ActionResult NotFound()
        {
            return View();
        }
    }
}

Sources/OS.Web/Controllers/SiteMapController.cs
using System.Web.Mvc;
using MvcSiteMapProvider.Web.Mvc.Filters;

namespace OS.Web.Controllers
{
    public class SiteMapController : Controller
    {
        [SiteMapCacheRelease]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Sources/OS.Web/Views/Shared/NotFound.cshtml
@model string

@{
    Layout = "_errorLayout.cshtml";
}

<div class="alert alert-warning" style="margin-top: 20px;">
        <h1 style="color: #d9534f">
            Помилка сервера
        </h1>
    <p>
        Сторінка @Request.Params["aspxerrorpath"] не знайдена
    </p>

    @if (ViewBag.ReferrerUrl != null)
    {
        <p>Поверрнутися на <a href="@ViewBag.ReferrerUrl">попередню сторінку</a>.</p>
    }
</div>

Sources/OS.Web/Views/Shared/_Layout.cshtml
@using OS.Configuration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/angular")
@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    var globalSettings = {
        consumerBasket: {
            maxProducts: parseInt("@Constants.ConsumerBasket.MAX_COUNT"), // paseInt because of otherwise warning about syntaxis error in editor
            minProducts: parseInt("@Constants.ConsumerBasket.MIN_COUNT")  // paseInt because of otherwise warning about syntaxis error in editor
        }
    };
</script>


@RenderSection("topSection")

<div class="container table-container wrapper">
    @RenderSection("content")

    <div class="push">
    </div>
</div>

<div class="footer container">
    <hr style="margin-top: 5px;"/>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p>&copy; @DateTime.Now.Year - @ApplicationSettings.Instance.AppSettings.ApplicationName</p>
                <p>
                    <b>Environment:</b> @ApplicationSettings.Instance.AppSettings.Environment
                </p>
                <p>
                    <span>
                        <b>Client:</b>
                    </span>
                    <span id="browserInfo"></span>
                </p>
            </div>
            <div class="col-md-2 col-md-offset-4">
                @{
                    string mailToTemplate = "mailto:jgrynco@gmail.com?Subject={0}: [коротка інформація про {1}]&cc=agrynco@gmail.com";
                    mailToTemplate += "&body=Тут максимально детально опишіть що саме Ви хочете. Не лінуйтеся і вкладіть картинки якщо це можливо";
                }
                <div class="row">
                    <a href='@string.Format(mailToTemplate, "OS_B", "помилку")'>Повідомити про помилку</a>
                </div>
                <div class="row">
                    <a href='@string.Format(mailToTemplate, "OS_Q", "запит")'>Запитати</a>
                </div>
                <div class="row">
                    <a href='@string.Format(mailToTemplate, "OS_US", "додатковий функціонал")'>Замовити додатковий функціонал</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById("browserInfo").innerHTML = navigator.userAgent;
</script>

@RenderSection("scripts")

</body>
</html>

Sources/OS.Web/Views/Shared/_accountLayout.cshtml
@{
    Layout = "_publicLayout.cshtml";
}

<table class="full-size">
    <tr>
        <td></td>
        <td width="1px">
            <h2>@PageData[Constants.PageData.PAGE_TITLE]</h2>
            <hr />
            @Html.ValidationSummary()

            @RenderBody()
        </td>
        <td></td>
    </tr>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sources/OS.Web/Views/Shared/_adminEditLayout.cshtml
@using OS.Web.Models
@model BaseCreateOrEditViewModel

@{
    Layout = "_adminLayout.cshtml";
}

@section content
{
    @{
        string currentControllerName = (string) ViewContext.RouteData.Values[Constants.RouteDataKeys.CONTROLLER];
    }

    @using (Html.BeginForm("Save", currentControllerName, FormMethod.Post, new
    {
        @class = "form-horizontal",
        role = "form",
        enctype = "multipart/form-data"
    }))
    {
        @Html.HiddenFor(m => m.Id)

        @RenderSection("editor")

        <div id="dialog-buttons" class="form-group" style="display: none">
            <label class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
                <span></span>
                <input type="reset" class="btn btn-default" value="Відміна" onclick="goBack()">
            </div>
        </div>
    }
}

@section scripts
{
    <script type="text/javascript">
        $().ready(function()
        {
            switch ($("#dialog-buttons-placeholder").length)
            {
                case 0:
                    $("#dialog-buttons").show();
                    break;
                case 1:
                    $("#dialog-buttons").detach().appendTo("#dialog-buttons-placeholder");
                    $("#dialog-buttons").show();
            }
        });

        function goBack()
        {
            if (confirm("Ви впевненні що хочете відмінити редагуквання?") === true)
            {
                window.history.back();
            }
        }
    </script>
    
    @RenderSection("scripts", false)
}

Sources/OS.Web/Views/Shared/_adminLayout.cshtml
@using OS.Configuration
@{
    Layout = "_layout.cshtml";
}

@section topSection
{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(ApplicationSettings.Instance.AppSettings.ApplicationName, "Index", "Home",
                    new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse row">
                <ul class="nav navbar-nav navbar-left">
                    <li>@Html.ActionLink("Категорії товарів", "Index", "ProductCategories")</li>
                    <li>@Html.ActionLink("Товари", "Index", "Products")</li>
                    <li>@Html.ActionLink("Бренди", "Index", "Brands")</li>
                    <li>@Html.ActionLink("Країни", "Index", "Countries")</li>

                    @Html.Partial("_commonMenuItems")
                </ul>

                <div class="navbar-right" style="margin-right: 15px;">
                    <ul class="nav navbar-nav">
                        @Html.Partial("_loginPartial")
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

@section content
{
    @if (!IsSectionDefined("breadcrumbs"))
    {
        @Html.MvcSiteMap().SiteMapPath("BootstrapSiteMapPathHelperModel")
    }
    else
    {
        @RenderSection("breadcrumbs")
    }

    @RenderSection("content")
}

@section scripts
{
    @RenderSection("scripts", false)
}

Sources/OS.Web/Views/Shared/_adminListLayout.cshtml
@{
    Layout = "_adminLayout.cshtml";
}


@if (IsSectionDefined("substituteBreadcrumbs"))
{
    @section breadcrumbs
    {
        @RenderSection("substituteBreadcrumbs")
    }
}

@section content
{
    @{
        string currentControllerName = (string) ViewContext.RouteData.Values[Constants.RouteDataKeys.CONTROLLER];
    }

    @if (IsSectionDefined("toolBar"))
    {
        @RenderSection("toolBar")
    }
    else
    {
        <div class="panel panel-default">
            <ul class="nav nav-pills">
                @if (IsSectionDefined("createToolBarItem"))
                {
                    @RenderSection("createToolBarItem")
                }
                else
                {
                    <li role="presentation">
                        @Html.ActionLink("Створити", "Create", currentControllerName)
                    </li>
                }
                <li role="presentation">
                    <a href="#">Видалити</a>
                </li>

                @if (IsSectionDefined("filter"))
                {
                    <li class="nav-divider"></li>
                    <li role="presentation">
                        <a href="#" class="btn btn-link" data-toggle="collapse" data-target="#filter-panel">
                            <span class="glyphicon glyphicon-cog"></span>Фільтер
                        </a>
                    </li>
                }

            </ul>
        </div>
    }

    @if (IsSectionDefined("filter"))
    {
        string listFilterFormName = "form-list-filter";

        <div class="container">
            <div class="row">
                <div id="filter-panel" class="collapse in filter-panel" aria-expanded="true">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @using (Html.BeginForm("Index", currentControllerName, FormMethod.Get, new
                                {
                                    id = listFilterFormName,
                                    @class = "form-inline",
                                    role = "form"
                                }))
                            {
                                @RenderSection("filter")
                                <div class="btn btn-primary" onclick="doSearch()">Шукати</div>

                                <script type="text/javascript">
                                    function doSearch()
                                    {
                                        $("#@listFilterFormName").submit();
                                    }
                                </script>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    @RenderSection("list")
}

@section scripts
{
    <script type="text/javascript">
        function confirmDelete()
        {
            return confirm("Ви впевнені що хочете видалити елемент?");
        }
    </script>

    @RenderSection("scripts", false)
}

Sources/OS.Web/Views/Shared/_commonMenuItems.cshtml
@using OS.Business.Domain
<li>
    @Html.ActionLink("Контакти", "Index", "HtmlContents", new
                   {
                       htmlContentCode = HtmlContentCode.Contacts
                   }, null)
</li>
<li>
    @Html.ActionLink("Про магазин", "Index", "HtmlContents", new
                   {
                       htmlContentCode = HtmlContentCode.About
                   }, null)
</li>

Sources/OS.Web/Views/Shared/_consumerBasket.cshtml
<a href="@Url.Action("Index", "ConsumerBasket")" id="consumerBasketLink" class="">Корзина
    <span id="basketCounter" class="badge">
        0
    </span>
</a>


<script src="~/Scripts/application/products/consumerBasket.js"></script>

<script type="text/javascript">
    var consumerBasket;

    $().ready(function ()
    {
        consumerBasket = new ConsumerBasket();
    });
</script>

Sources/OS.Web/Views/Shared/_publicLayout.cshtml
@using OS.Configuration
@{
    Layout = "_layout.cshtml";
}

@section topSection
{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(ApplicationSettings.Instance.AppSettings.ApplicationName, "Index", "Home",
                    new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse row">
                <ul class="nav navbar-nav navbar-left">
                    @Html.Partial("_commonMenuItems")
                    <li>@Html.ActionLink("Карта сайту", "Index", "SiteMap")</li>
                    @if (Request.IsAuthenticated && Request.RequestContext.HttpContext.User.IsInRole("admin"))
                    {
                        <li>
                            @Html.ActionLink("Адміністрування", "Index", "ProductCategories", null, new
                                {
                                    style = "color: red;"
                                })
                        </li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right" style="margin-right: 15px;">
                    <li>
                        @Html.Partial("_searchControl")
                    </li>
                    @Html.Partial("_loginPartial")

                    <li>@Html.Partial("_consumerBasket")</li>
                </ul>
            </div>
        </div>
    </div>
}

@section content
{
    <div class="row table-row">
        <div class="col-md-2 table-col" style="padding-left: 0; padding-right: 0">
            @if (IsSectionDefined("leftMenu"))
            {
                @RenderSection("leftMenu")
            }
            else
            {
                @Html.Action("VerticalCategorySelector", "Categories")
            }

        </div>
        <div class="col-md-10 table-col" style="background: white; padding: 10px;">
            @Html.MvcSiteMap().SiteMapPath("BootstrapSiteMapPathHelperModel")
            @RenderBody()
        </div>
        @*<div class="col-md-3 table-col" style="background: lightgray"></div>*@
    </div>
}

@section scripts
{
    @RenderSection("scripts")
}

Sources/OS.Web/Views/Shared/_requiredMark.cshtml
<span class="requiredMark">
    *
</span>

Sources/OS.Web/Views/Shared/_searchControl.cshtml
<form class="navbar-form" role="search">
    <div class="input-group" style="width: 200px;">
        <input type="text" id="tbSearchProducts" class="form-control" placeholder="Що ви бажаєте купити?" name="searchTerm">
        <span class="input-group-btn" onclick="$('#searchForm').submit();">
            <button class="btn btn-danger" type="submit">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </span>
    </div>
</form>

<script type="text/javascript">
    $("#tbSearchProducts").autocomplete(
       {
           source: "/api/products/autocomplete",
           minLength: 1,
           create: function ()
           {
               $(this).data('ui-autocomplete')._renderItem = function (ul, item)
               {
                   return $('<li>')
                       .append('<a>' + item.label.replace(this.term, "<b>" + this.term + "</b>") + '</a>')
                       .appendTo(ul);
               };
           }
       });
</script>

Sources/OS.Web/Views/Shared/_verticalCategorySelector.cshtml
@using OS.Web.Controllers
@model VerticalCategorySelectorViewModel

<!-- SmartMenus core CSS (required) -->
<link href="~/Scripts/SmartMenus/css/sm-core-css.css" rel="stylesheet" />

<!-- "sm-blue" menu theme (optional, you can use your own CSS, too) -->
<link href="~/Scripts/SmartMenus/css/sm-mint/sm-mint.css" rel="stylesheet" />

<!-- #main-menu config - instance specific stuff not covered in the theme -->
<!-- Put this in an external stylesheet if you want the media query to work in IE8 (e.g. where the rest of your page styles are) -->
<style type="text/css">
    @@media (min-width: 768px) {
        #main-menu {
            float: left;
            position: relative;
            /*z-index: 9999;*/
            width: 100%;
        }

            #main-menu ul {
                width: 12em; /* fixed width only please - you can use the "subMenusMinWidth"/"subMenusMaxWidth" script options to override this if you like */
            }
    }
</style>

<!-- Respond.js for IE8 support of media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- jQuery -->
<!-- SmartMenus jQuery plugin -->
<script src="~/Scripts/SmartMenus/jquery.smartmenus.js"></script>

<!-- SmartMenus jQuery init -->
<script type="text/javascript">
    $(function ()
    {
        $('#main-menu').smartmenus({
            mainMenuSubOffsetX: 1,
            mainMenuSubOffsetY: -8,
            subMenusSubOffsetX: 1,
            subMenusSubOffsetY: -8,
            subIndicators: true
        });
    });
</script>

<nav role="navigation">
    <!-- Sample menu definition -->
    <ul id="main-menu" class="sm sm-vertical sm-mint">
        @foreach (VerticalCategorySelectorItemViewModel category in Model.Categories)
        {
            <li>
                @Html.Partial("_verticalCategorySelectorItem", category)
                @Html.Partial("_verticalCategorySelectorChildItems", category.ChildCategories)
            </li>
        }
    </ul>
</nav>

Sources/OS.Web/Views/Shared/_verticalCategorySelectorChildItems.cshtml
@using OS.Web.Controllers
@model List<VerticalCategorySelectorItemViewModel>

@if (Model.Count > 0)
{
    <ul>
        @foreach (VerticalCategorySelectorItemViewModel category in Model)
        {
            <li>
                @Html.Partial("_verticalCategorySelectorItem", category)
                @Html.Partial("_verticalCategorySelectorChildItems", category.ChildCategories)
            </li>
        }
    </ul>
}

Sources/OS.Web/Views/Shared/_verticalCategorySelectorItem.cshtml
@using OS.Web.Controllers
@model VerticalCategorySelectorItemViewModel
<div>
    <span>
        @Html.ActionLink(string.Format("{0} ({1})", Model.Name, Model.ProductsCount), "ChangeCategory", "Home", new
            {
                categoryId = Model.Id
            }, null)
    </span>

</div>